# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('fail', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Feature')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Panel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Version')),
            ],
        ),
    ]
