# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160609_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationresult',
            name='passed',
            field=models.IntegerField(default=0),
        ),
    ]
