# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_automationresult_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationresult',
            name='version_name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
