# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_automationresult_version_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ManyToManyField(to='dashboard.Feature', verbose_name='Features')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Panel')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Version')),
            ],
        ),
    ]
