# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160701_1119'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='featurematching',
            order_with_respect_to=None,
        ),
    ]
