# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160701_1128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CasesHistory',
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['name']},
        ),
    ]
